[theme]
base = "light"
primaryColor = "#E694FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F5"
textColor = "#262730"
font = "sans serif"

[layout]
initial_sidebar_state = "expanded"

[server]
headless = true

[browser]
gatherUsageStats = false
